### ISSUE TITLE
Doesnt work when in controller mode

### ISSUE THREAD

**Issue by Reserton** [Eternita-S/AntiAfkKick#16]
It appears because it uses the ctrl key,this does not work when using a controller. However once controller is removed it works.

Any chance this could also send a controller button press to work with both methods?

**Comment by Eternita-S** [comment]
Nah, this is not caused by which key is sent but by controller constantly sending input events to windows while it should not. More about the issue here: https://github.com/xaviergmail/DiscordNotificationDebug

Preferably just use Dalamud plugin - it reads afk timer from the game instead of Windows. And therefore has no need to rely on Windows  timer which gets messed by apparently controller drivers. Or you could also alt-tab out of the game if you want to use act/standalone version with controller.

**Comment by Latenja** [comment]
i don't use a controller for FF14 but had it hooked up to my PC due to the long maintenance of 24 hrs i was playing FFVI to pass the time. Maybe that was the problem? I unplugged it from my PC so now i will see if that was the problem.

Thanks for the quick reply, it is very much appreciated. <3
