### ISSUE TITLE
ACT plugin not working?

### ISSUE THREAD

**Issue by sonholion** [Eternita-S/AntiAfkKick#9]
Heyo,
Been trying to get the plugin to work for 4hours now and It just doesnt seem to be sending any keypresses to my XIV client.
Installed it the usual way, have tried redownloading the plugin, ACT itself etc and notthing seems to work, sadly..
Is this plugin in need of an update to work with the latest ACT update?

Cheers

**Comment by Eternita-S** [comment]
Hello!
Does text like this (sending keypress to ffxiv window) appears in act's plugins section? 
![image](https://user-images.githubusercontent.com/5073202/145684297-756abeec-eb8b-4c24-838a-33766c3bfa1e.png)

**Comment by sonholion** [comment]
![image](https://user-images.githubusercontent.com/95966473/145684356-85b82303-0493-4fad-a962-d3648a96ebd5.png)
Yes it does, sometimes. Sometimes it just says that the threads are starting or is ready

**Comment by Eternita-S** [comment]
https://github.com/xaviergmail/DiscordNotificationDebug/releases/tag/v1.1
Download and run InputDebugger.exe from there and see if your system is being able to recognize idle state

**Comment by sonholion** [comment]
I did run the program and removed a device that made not idle. However, the plugin is now stuck on "thread started" once again and doesnt queue the next button press? I did try to restart ACT to see if it fixed it but not yet

**Comment by Eternita-S** [comment]
so now InputDebugger is able to recognize your system being idle, but there are still no keypresses, right? They should happen within 4 minutes at most once you stopping being active.
What about when the game is not active (you're in chrome/discord/etc)?

**Comment by sonholion** [comment]
If im on chrome etc and not using my keyboard or mouse it still say idle. However, the plugin does say that its sending keypresses now but I cant detact any movement or anything while watching XIV like a hawk to see if it actualy is doing it

**Comment by Eternita-S** [comment]
Can you open inputdebugger.exe, switch to ffxiv and see if it's able to detect system being idle?
If it's able to detect system idle when you aren't doing anything, then it'll work fine.
If it can't detect system being idle, then it won't work while ffxiv is focused unfortunately. 
If ffxiv is not active application, plugin works regardless of what is happening with idle timer.
There won't be any movement in ffxiv because you don't need to move to reset afk timer. To test it without risking being logged out, go into any dungeon solo and see if in 5+ minutes of inactivity messages about you being idle will appear.

**Comment by sonholion** [comment]
It seems to work now! Cheers for the amazing and fast support mate ! :D
